'use client'

import { Navbar } from '@/components/layout/Navbar'
import { Footer } from '@/components/layout/Footer'

export default function CodeOfConductPage() {
  return (
    <div className="min-h-screen bg-white text-[#5a5a5a] flex flex-col font-sans">
      <Navbar />

      {/* Hero Section */}
      <section className="pt-32 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-[4px] bg-[#f5f5f5] text-[#080808] text-xs font-medium uppercase tracking-[1.5px] mb-6 border border-[#d8d8d8]">
            Policies &amp; Guidelines
          </div>
          <h1 className="text-4xl sm:text-5xl font-semibold text-[#080808] mb-4 tracking-[-0.8px]">Code of Conduct</h1>
          <p className="text-lg sm:text-xl text-[#5a5a5a] leading-relaxed">IEEE CIS Summer School Participant Guidelines</p>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <p className="mb-4 text-base leading-relaxed">The IEEE CIS Summer School is intended to provide a safe, inclusive, professional, and intellectually stimulating environment for students, researchers, faculty members, speakers, volunteers, organizers, and other participants.</p>
          <p className="mb-4 text-base leading-relaxed">The event aims to encourage learning, technical discussion, collaboration, networking, and the responsible exchange of ideas in accordance with IEEE&apos;s commitment to integrity, professionalism, respect, and responsible conduct.</p>
          <p className="mb-4 text-base leading-relaxed">This Code of Conduct establishes the standards of behavior expected from everyone participating in or contributing to the Summer School.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">2. SCOPE</h2>
          <p className="mb-4 text-base leading-relaxed">This Code of Conduct applies to all participants associated with the IEEE CIS Summer School, including:</p>
          <p className="mb-4 text-base leading-relaxed">Students and delegates</p>
          <p className="mb-4 text-base leading-relaxed">Speakers and invited experts</p>
          <p className="mb-4 text-base leading-relaxed">Faculty members and mentors</p>
          <p className="mb-4 text-base leading-relaxed">Organizing committee members</p>
          <p className="mb-4 text-base leading-relaxed">Volunteers and student coordinators</p>
          <p className="mb-4 text-base leading-relaxed">Sponsors and exhibitors</p>
          <p className="mb-4 text-base leading-relaxed">Guests and visitors</p>
          <p className="mb-4 text-base leading-relaxed">Technical and administrative staff</p>
          <p className="mb-4 text-base leading-relaxed">Online/virtual participants, where applicable</p>
          <p className="mb-4 text-base leading-relaxed">The guidelines apply during:</p>
          <p className="mb-4 text-base leading-relaxed">Technical sessions</p>
          <p className="mb-4 text-base leading-relaxed">Workshops and tutorials</p>
          <p className="mb-4 text-base leading-relaxed">Keynote and invited talks</p>
          <p className="mb-4 text-base leading-relaxed">Hands-on sessions</p>
          <p className="mb-4 text-base leading-relaxed">Networking sessions</p>
          <p className="mb-4 text-base leading-relaxed">Social and cultural activities organized as part of the event</p>
          <p className="mb-4 text-base leading-relaxed">Official transportation and event-related activities</p>
          <p className="mb-4 text-base leading-relaxed">Online meetings, discussion forums, chats, and other official digital platforms</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">3. IEEE PRINCIPLES</h2>
          <p className="mb-4 text-base leading-relaxed">The Summer School follows the principles established by IEEE for professional and ethical conduct.</p>
          <p className="mb-4 text-base leading-relaxed">All participants are expected to:</p>
          <p className="mb-4 text-base leading-relaxed">Act with integrity and professionalism.</p>
          <p className="mb-4 text-base leading-relaxed">Treat others with dignity and respect.</p>
          <p className="mb-4 text-base leading-relaxed">Respect different opinions, backgrounds, experiences, and perspectives.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain an environment free from discrimination, harassment, bullying, and intimidation.</p>
          <p className="mb-4 text-base leading-relaxed">Respect the privacy and personal information of others.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid actions that may harm another person&apos;s reputation, property, data, or professional standing.</p>
          <p className="mb-4 text-base leading-relaxed">Contribute positively to the academic and professional environment of the event.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s official Code of Conduct emphasizes respect, fairness, protection of personal information, and avoidance of harassment, discrimination, bullying, malicious conduct, and abuse.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">4. RESPECTFUL AND PROFESSIONAL BEHAVIOR</h2>
          <p className="mb-4 text-base leading-relaxed">All participants are expected to behave professionally throughout the event.</p>
          <p className="mb-4 text-base leading-relaxed">Participants should:</p>
          <p className="mb-4 text-base leading-relaxed">Communicate respectfully with speakers, organizers, volunteers, staff, and fellow participants.</p>
          <p className="mb-4 text-base leading-relaxed">Listen attentively during technical sessions.</p>
          <p className="mb-4 text-base leading-relaxed">Allow others to express their views without unnecessary interruption.</p>
          <p className="mb-4 text-base leading-relaxed">Ask questions in a constructive and relevant manner.</p>
          <p className="mb-4 text-base leading-relaxed">Respect differences of opinion during technical discussions.</p>
          <p className="mb-4 text-base leading-relaxed">Follow reasonable instructions provided by organizers and event staff.</p>
          <p className="mb-4 text-base leading-relaxed">Use professional language in verbal and written communication.</p>
          <p className="mb-4 text-base leading-relaxed">Respect the facilities, equipment, and property of the host institution.</p>
          <p className="mb-4 text-base leading-relaxed">Disagreement with another participant&apos;s technical opinion is acceptable; personal attacks, insults, intimidation, or degrading comments are not.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">5. NON-DISCRIMINATION AND ANTI-HARASSMENT</h2>
          <p className="mb-4 text-base leading-relaxed">The IEEE CIS Summer School is committed to maintaining an inclusive and harassment-free environment.</p>
          <p className="mb-4 text-base leading-relaxed">Discrimination, harassment, bullying, intimidation, or threatening behavior will not be tolerated.</p>
          <p className="mb-4 text-base leading-relaxed">Unacceptable behavior includes, but is not limited to:</p>
          <p className="mb-4 text-base leading-relaxed">Verbal abuse or threats</p>
          <p className="mb-4 text-base leading-relaxed">Personal insults or degrading comments</p>
          <p className="mb-4 text-base leading-relaxed">Bullying or intimidation</p>
          <p className="mb-4 text-base leading-relaxed">Unwelcome sexual attention</p>
          <p className="mb-4 text-base leading-relaxed">Sexual harassment</p>
          <p className="mb-4 text-base leading-relaxed">Stalking</p>
          <p className="mb-4 text-base leading-relaxed">Unwanted physical contact</p>
          <p className="mb-4 text-base leading-relaxed">Offensive or discriminatory remarks</p>
          <p className="mb-4 text-base leading-relaxed">Harassing photography or recording</p>
          <p className="mb-4 text-base leading-relaxed">Repeated unwanted communication</p>
          <p className="mb-4 text-base leading-relaxed">Deliberate exclusion or intimidation</p>
          <p className="mb-4 text-base leading-relaxed">Online harassment through event-related digital platforms</p>
          <p className="mb-4 text-base leading-relaxed">No participant should be discriminated against on the basis of characteristics protected by applicable law or IEEE policy.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s event guidance explicitly states that IEEE events should provide a safe, productive, and welcoming environment and that IEEE does not tolerate discrimination, harassment, or bullying at IEEE-related events.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">6. ACADEMIC AND TECHNICAL INTEGRITY</h2>
          <p className="mb-4 text-base leading-relaxed">The Summer School is primarily an academic and technical learning environment. Participants are expected to maintain high standards of academic and professional integrity.</p>
          <p className="mb-4 text-base leading-relaxed">Participants must:</p>
          <p className="mb-4 text-base leading-relaxed">Give appropriate credit to the original creators of ideas, software, datasets, research, images, and other materials.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid plagiarism and unauthorized copying.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid misrepresenting another person&apos;s work as their own.</p>
          <p className="mb-4 text-base leading-relaxed">Clearly distinguish personal work from collaborative work.</p>
          <p className="mb-4 text-base leading-relaxed">Follow the instructions provided by speakers or instructors during hands-on sessions.</p>
          <p className="mb-4 text-base leading-relaxed">Respect software licenses, intellectual-property rights, and applicable institutional policies.</p>
          <p className="mb-4 text-base leading-relaxed">Use of AI tools, programming assistants, or other technologies during assignments, demonstrations, or activities should follow the rules specified by the respective instructor or organizer.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">7. PARTICIPATION AND SESSION ETIQUETTE</h2>
          <p className="mb-4 text-base leading-relaxed">Participants are expected to contribute to a productive learning environment.</p>
          <p className="mb-4 text-base leading-relaxed">During technical sessions:</p>
          <p className="mb-4 text-base leading-relaxed">Arrive on time.</p>
          <p className="mb-4 text-base leading-relaxed">Keep mobile phones on silent mode.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid unnecessary conversations during presentations.</p>
          <p className="mb-4 text-base leading-relaxed">Do not interrupt speakers except when appropriate.</p>
          <p className="mb-4 text-base leading-relaxed">Follow the designated procedure for asking questions.</p>
          <p className="mb-4 text-base leading-relaxed">Keep questions concise and relevant.</p>
          <p className="mb-4 text-base leading-relaxed">Respect the allotted time for presentations and discussions.</p>
          <p className="mb-4 text-base leading-relaxed">Do not leave sessions repeatedly without necessity.</p>
          <p className="mb-4 text-base leading-relaxed">During workshops and hands-on sessions:</p>
          <p className="mb-4 text-base leading-relaxed">Follow instructor and volunteer instructions.</p>
          <p className="mb-4 text-base leading-relaxed">Do not intentionally disrupt demonstrations or activities.</p>
          <p className="mb-4 text-base leading-relaxed">Do not interfere with another participant&apos;s system, code, files, or equipment.</p>
          <p className="mb-4 text-base leading-relaxed">Report technical problems to the assigned volunteers or organizers.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">8. USE OF PHOTOGRAPHY, VIDEO, AND RECORDING</h2>
          <p className="mb-4 text-base leading-relaxed">Participants should respect the privacy and preferences of other attendees.</p>
          <p className="mb-4 text-base leading-relaxed">Unless explicitly permitted by the organizers:</p>
          <p className="mb-4 text-base leading-relaxed">Do not record private conversations.</p>
          <p className="mb-4 text-base leading-relaxed">Do not photograph or record individuals in a manner that is intrusive, disruptive, or unwelcome.</p>
          <p className="mb-4 text-base leading-relaxed">Do not record confidential discussions or unpublished research without permission.</p>
          <p className="mb-4 text-base leading-relaxed">Do not distribute recordings containing identifiable participants without appropriate consent.</p>
          <p className="mb-4 text-base leading-relaxed">Official event photography or videography may be conducted by authorized members of the organizing team for documentation and promotional purposes, subject to applicable institutional and IEEE policies.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">9. PRIVACY AND PERSONAL INFORMATION</h2>
          <p className="mb-4 text-base leading-relaxed">Participants must respect the personal information of others.</p>
          <p className="mb-4 text-base leading-relaxed">Do not:</p>
          <p className="mb-4 text-base leading-relaxed">Share another participant&apos;s phone number, email address, identification details, or other personal information without permission.</p>
          <p className="mb-4 text-base leading-relaxed">Collect personal information for unauthorized purposes.</p>
          <p className="mb-4 text-base leading-relaxed">Share private photographs, messages, or conversations without consent.</p>
          <p className="mb-4 text-base leading-relaxed">Use event registration information for unauthorized promotional or commercial purposes.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s Code of Conduct specifically includes respect for privacy and protection of personal information and data.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">10. ONLINE AND DIGITAL CONDUCT</h2>
          <p className="mb-4 text-base leading-relaxed">Where the Summer School uses online platforms, social media groups, messaging applications, learning-management systems, or virtual meeting platforms, the same standards of conduct apply.</p>
          <p className="mb-4 text-base leading-relaxed">Participants must:</p>
          <p className="mb-4 text-base leading-relaxed">Use respectful language.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid spam and unnecessary messages.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid harassment or targeted abuse.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid sharing offensive or discriminatory material.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid unauthorized access to another person&apos;s account or system.</p>
          <p className="mb-4 text-base leading-relaxed">Respect intellectual property and confidentiality.</p>
          <p className="mb-4 text-base leading-relaxed">Follow the rules of the platform being used.</p>
          <p className="mb-4 text-base leading-relaxed">The Code of Conduct applies to official event-related digital interactions as well as physical event activities.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">11. SAFETY AND SECURITY</h2>
          <p className="mb-4 text-base leading-relaxed">The safety of participants is a shared responsibility.</p>
          <p className="mb-4 text-base leading-relaxed">Participants should:</p>
          <p className="mb-4 text-base leading-relaxed">Follow instructions from event organizers, college authorities, security personnel, and venue staff.</p>
          <p className="mb-4 text-base leading-relaxed">Familiarize themselves with emergency exits and designated assembly areas.</p>
          <p className="mb-4 text-base leading-relaxed">Immediately report safety hazards to the organizing team.</p>
          <p className="mb-4 text-base leading-relaxed">Not tamper with fire alarms, safety equipment, electrical installations, or emergency systems.</p>
          <p className="mb-4 text-base leading-relaxed">Not enter restricted areas.</p>
          <p className="mb-4 text-base leading-relaxed">Carry their event identification/access pass when required.</p>
          <p className="mb-4 text-base leading-relaxed">Follow applicable college and venue safety regulations.</p>
          <p className="mb-4 text-base leading-relaxed">In the event of an emergency, participants must follow the instructions of authorized personnel and move to the designated safe area.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s conference guidance emphasizes advance preparation for emergencies and the creation of safe and welcoming event environments.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">12. ALCOHOL, DRUGS, AND PROHIBITED SUBSTANCES</h2>
          <p className="mb-4 text-base leading-relaxed">The possession, use, distribution, or being under the influence of illegal drugs or other prohibited substances during the Summer School or within the event premises is strictly prohibited.</p>
          <p className="mb-4 text-base leading-relaxed">Alcohol consumption is prohibited at the event unless specifically permitted by the host institution and applicable law.</p>
          <p className="mb-4 text-base leading-relaxed">Any participant whose behavior creates a safety risk or substantially disrupts the event may be removed from the activity or venue.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">13. CAMPUS AND VENUE GUIDELINES</h2>
          <p className="mb-4 text-base leading-relaxed">All participants must comply with the rules of the host institution and event venue.</p>
          <p className="mb-4 text-base leading-relaxed">Participants should:</p>
          <p className="mb-4 text-base leading-relaxed">Maintain cleanliness.</p>
          <p className="mb-4 text-base leading-relaxed">Use classrooms, laboratories, auditoriums, and other facilities responsibly.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid damaging college or venue property.</p>
          <p className="mb-4 text-base leading-relaxed">Use equipment only for its intended purpose.</p>
          <p className="mb-4 text-base leading-relaxed">Follow laboratory and equipment-specific safety instructions.</p>
          <p className="mb-4 text-base leading-relaxed">Respect restricted-access areas.</p>
          <p className="mb-4 text-base leading-relaxed">Dispose of waste in designated locations.</p>
          <p className="mb-4 text-base leading-relaxed">Follow parking and transportation instructions where applicable.</p>
          <p className="mb-4 text-base leading-relaxed">Any damage caused intentionally or through serious negligence may be referred to the appropriate institutional authority.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">14. ORGANIZER AND VOLUNTEER RESPONSIBILITIES</h2>
          <p className="mb-4 text-base leading-relaxed">The organizing committee is responsible for making reasonable efforts to maintain a safe, respectful, and productive environment.</p>
          <p className="mb-4 text-base leading-relaxed">Organizers and volunteers should:</p>
          <p className="mb-4 text-base leading-relaxed">Treat all participants respectfully.</p>
          <p className="mb-4 text-base leading-relaxed">Provide clear information and instructions.</p>
          <p className="mb-4 text-base leading-relaxed">Assist participants with reasonable event-related queries.</p>
          <p className="mb-4 text-base leading-relaxed">Respond appropriately to safety or conduct concerns.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain confidentiality when handling sensitive complaints.</p>
          <p className="mb-4 text-base leading-relaxed">Escalate serious incidents to the appropriate authority.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid favoritism or discriminatory treatment.</p>
          <p className="mb-4 text-base leading-relaxed">Ensure that event procedures are applied consistently.</p>
          <p className="mb-4 text-base leading-relaxed">Volunteers should not attempt to personally investigate serious allegations or confront an alleged offender beyond what is necessary to maintain immediate safety. Serious concerns should be escalated to the designated event authority.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">15. REPORTING A CONCERN OR VIOLATION</h2>
          <p className="mb-4 text-base leading-relaxed">Participants are encouraged to report conduct that violates this Code of Conduct.</p>
          <p className="mb-4 text-base leading-relaxed">Concerns may be reported to:</p>
          <p className="mb-4 text-base leading-relaxed">Event Conduct / Grievance Contact:</p>
          <p className="mb-4 text-base leading-relaxed">Name:</p>
          <p className="mb-4 text-base leading-relaxed">Designation:</p>
          <p className="mb-4 text-base leading-relaxed">Email:</p>
          <p className="mb-4 text-base leading-relaxed">Phone:</p>
          <p className="mb-4 text-base leading-relaxed">Faculty Coordinator:</p>
          <p className="mb-4 text-base leading-relaxed">Name:</p>
          <p className="mb-4 text-base leading-relaxed">Email:</p>
          <p className="mb-4 text-base leading-relaxed">Phone:</p>
          <p className="mb-4 text-base leading-relaxed">Event Organizing Committee:</p>
          <p className="mb-4 text-base leading-relaxed">[Official Email / Contact Number]</p>
          <p className="mb-4 text-base leading-relaxed">For immediate safety concerns, participants should contact:</p>
          <p className="mb-4 text-base leading-relaxed">College Security:</p>
          <p className="mb-4 text-base leading-relaxed">Emergency Services:</p>
          <p className="mb-4 text-base leading-relaxed">Venue Emergency Contact:</p>
          <p className="mb-4 text-base leading-relaxed">Participants may also approach any designated event organizer or volunteer, who will direct the concern to the appropriate authority.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s official Event Conduct & Safety Statement similarly directs participants to report inappropriate behaviour to on-site staff, security, venue personnel, or the designated IEEE reporting channel.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">16. HANDLING OF COMPLAINTS</h2>
          <p className="mb-4 text-base leading-relaxed">Reports will be handled as seriously and discreetly as reasonably possible.</p>
          <p className="mb-4 text-base leading-relaxed">Depending on the nature and severity of the incident, the organizing committee may:</p>
          <p className="mb-4 text-base leading-relaxed">Receive and document the concern.</p>
          <p className="mb-4 text-base leading-relaxed">Ensure the immediate safety of the individuals involved.</p>
          <p className="mb-4 text-base leading-relaxed">Refer the matter to the faculty coordinator, college authority, IEEE authority, security personnel, or other appropriate authority.</p>
          <p className="mb-4 text-base leading-relaxed">Review relevant information and available evidence.</p>
          <p className="mb-4 text-base leading-relaxed">Take appropriate corrective or disciplinary action.</p>
          <p className="mb-4 text-base leading-relaxed">Refer serious matters to the appropriate institutional, legal, or IEEE authority.</p>
          <p className="mb-4 text-base leading-relaxed">Retaliation against a person who raises a genuine concern or participates in a complaint process is not acceptable.</p>
          <p className="mb-4 text-base leading-relaxed">The handling of complaints will be subject to applicable IEEE policies, institutional regulations, and Indian law.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s policies provide mechanisms for addressing discrimination, harassment, bullying, and retaliation and provide for escalation of serious matters to the appropriate IEEE authorities.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">17. POSSIBLE ACTIONS FOR VIOLATIONS</h2>
          <p className="mb-4 text-base leading-relaxed">Depending on the seriousness and circumstances of the violation, actions may include:</p>
          <p className="mb-4 text-base leading-relaxed">Verbal warning</p>
          <p className="mb-4 text-base leading-relaxed">Formal warning</p>
          <p className="mb-4 text-base leading-relaxed">Removal from a particular session</p>
          <p className="mb-4 text-base leading-relaxed">Removal from the event</p>
          <p className="mb-4 text-base leading-relaxed">Restriction of access to event facilities</p>
          <p className="mb-4 text-base leading-relaxed">Referral to college authorities</p>
          <p className="mb-4 text-base leading-relaxed">Referral to IEEE authorities</p>
          <p className="mb-4 text-base leading-relaxed">Cancellation of event participation</p>
          <p className="mb-4 text-base leading-relaxed">Reporting to appropriate legal or security authorities where required</p>
          <p className="mb-4 text-base leading-relaxed">Serious violations may result in immediate removal from the event without a prior warning.</p>
          <p className="mb-4 text-base leading-relaxed">Nothing in this document prevents the host institution, IEEE, or competent authorities from taking further action under applicable policies, regulations, or law.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">18. PARTICIPANT RESPONSIBILITIES</h2>
          <p className="mb-4 text-base leading-relaxed">By registering for or participating in the IEEE CIS Summer School, participants are expected to:</p>
          <p className="mb-4 text-base leading-relaxed">Read and follow this Code of Conduct.</p>
          <p className="mb-4 text-base leading-relaxed">Follow reasonable instructions from organizers and venue authorities.</p>
          <p className="mb-4 text-base leading-relaxed">Behave respectfully toward all participants.</p>
          <p className="mb-4 text-base leading-relaxed">Protect event property and facilities.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain academic and professional integrity.</p>
          <p className="mb-4 text-base leading-relaxed">Respect privacy and personal boundaries.</p>
          <p className="mb-4 text-base leading-relaxed">Report serious safety or conduct concerns.</p>
          <p className="mb-4 text-base leading-relaxed">Comply with applicable college, IEEE, and legal requirements.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">19. GUIDELINES FOR SPEAKERS AND TRAINERS</h2>
          <p className="mb-4 text-base leading-relaxed">Speakers, trainers, mentors, and invited experts are requested to:</p>
          <p className="mb-4 text-base leading-relaxed">Begin and conclude sessions according to the assigned schedule.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain a professional and inclusive environment.</p>
          <p className="mb-4 text-base leading-relaxed">Respect participants&apos; questions and viewpoints.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid discriminatory, harassing, or offensive content unrelated to the legitimate educational purpose of the session.</p>
          <p className="mb-4 text-base leading-relaxed">Clearly identify third-party materials and intellectual property where appropriate.</p>
          <p className="mb-4 text-base leading-relaxed">Inform organizers of any technical or logistical requirements in advance.</p>
          <p className="mb-4 text-base leading-relaxed">Follow the event&apos;s photography, recording, and confidentiality requirements.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">20. GUIDELINES FOR ORGANIZERS AND VOLUNTEERS</h2>
          <p className="mb-4 text-base leading-relaxed">Organizers and volunteers should:</p>
          <p className="mb-4 text-base leading-relaxed">Report to their assigned location on time.</p>
          <p className="mb-4 text-base leading-relaxed">Wear or carry appropriate identification.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain clear communication with the organizing committee.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid unnecessary disruption of technical sessions.</p>
          <p className="mb-4 text-base leading-relaxed">Assist participants in a polite and professional manner.</p>
          <p className="mb-4 text-base leading-relaxed">Escalate safety, security, medical, or conduct concerns promptly.</p>
          <p className="mb-4 text-base leading-relaxed">Avoid making unauthorized commitments on behalf of IEEE or the institution.</p>
          <p className="mb-4 text-base leading-relaxed">Maintain confidentiality regarding sensitive participant information.</p>
          <p className="mb-4 text-base leading-relaxed">Keep accurate records of important event-related incidents where required.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE Student Branch guidance emphasizes planning, organization, teamwork, communication, and clear responsibilities as important elements of successful student activities.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">21. ATTENDANCE AND REGISTRATION</h2>
          <p className="mb-4 text-base leading-relaxed">Participants should:</p>
          <p className="mb-4 text-base leading-relaxed">Complete registration using accurate information.</p>
          <p className="mb-4 text-base leading-relaxed">Carry valid identification where required.</p>
          <p className="mb-4 text-base leading-relaxed">Wear/display the event badge or access pass where applicable.</p>
          <p className="mb-4 text-base leading-relaxed">Attend only the sessions or activities for which they are authorized.</p>
          <p className="mb-4 text-base leading-relaxed">Inform organizers in advance where attendance requirements apply.</p>
          <p className="mb-4 text-base leading-relaxed">Follow any capacity or access restrictions established for specific sessions.</p>
          <p className="mb-4 text-base leading-relaxed">Event badges, passes, certificates, or other participation benefits may be subject to the event&apos;s registration and attendance requirements.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">22. CERTIFICATES AND PARTICIPATION</h2>
          <p className="mb-4 text-base leading-relaxed">Certificates of participation, completion, or other recognition may be subject to attendance and participation requirements communicated by the organizing committee.</p>
          <p className="mb-4 text-base leading-relaxed">The organizing committee reserves the right to withhold or revoke event recognition where participation is found to have violated applicable event, institutional, or IEEE requirements.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">23. ACCESSIBILITY AND INCLUSION</h2>
          <p className="mb-4 text-base leading-relaxed">The organizing team should make reasonable efforts to ensure that participants can access and participate in the event.</p>
          <p className="mb-4 text-base leading-relaxed">Participants requiring accessibility-related assistance are encouraged to communicate their requirements to the organizers as early as possible.</p>
          <p className="mb-4 text-base leading-relaxed">The organizing committee will make reasonable efforts, subject to available facilities and applicable institutional policies, to support accessibility requirements.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE&apos;s conference guidance specifically identifies accessibility as an important component of creating safe and welcoming conferences.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">24. SOCIAL MEDIA AND PUBLIC COMMUNICATION</h2>
          <p className="mb-4 text-base leading-relaxed">Participants are welcome to share their experiences from the Summer School while respecting:</p>
          <p className="mb-4 text-base leading-relaxed">Privacy of other participants.</p>
          <p className="mb-4 text-base leading-relaxed">Speaker preferences and recording restrictions.</p>
          <p className="mb-4 text-base leading-relaxed">Confidential or unpublished information.</p>
          <p className="mb-4 text-base leading-relaxed">Intellectual property rights.</p>
          <p className="mb-4 text-base leading-relaxed">IEEE and institutional branding guidelines.</p>
          <p className="mb-4 text-base leading-relaxed">Official statements on behalf of the Summer School, IEEE CIS, or the host institution may only be issued by authorized representatives.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">25. CHANGES TO THE GUIDELINES</h2>
          <p className="mb-4 text-base leading-relaxed">The organizing committee reserves the right to make reasonable modifications to these guidelines when required for:</p>
          <p className="mb-4 text-base leading-relaxed">Safety</p>
          <p className="mb-4 text-base leading-relaxed">Security</p>
          <p className="mb-4 text-base leading-relaxed">Operational requirements</p>
          <p className="mb-4 text-base leading-relaxed">Venue regulations</p>
          <p className="mb-4 text-base leading-relaxed">Institutional policies</p>
          <p className="mb-4 text-base leading-relaxed">IEEE requirements</p>
          <p className="mb-4 text-base leading-relaxed">Applicable laws or regulations</p>
          <p className="mb-4 text-base leading-relaxed">Significant changes should be communicated to participants through the official event communication channels.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">26. ACKNOWLEDGEMENT</h2>
          <p className="mb-4 text-base leading-relaxed">By registering for and/or participating in the IEEE CIS Summer School, participants acknowledge that they have read and understood these Code of Conduct and Participant Guidelines and agree to comply with them.</p>
          <p className="mb-4 text-base leading-relaxed">Participants are encouraged to contribute to an environment that reflects the values of IEEE: integrity, respect, professionalism, inclusion, responsible conduct, and the advancement of technology for humanity.</p>
          <h2 className="text-2xl font-semibold text-[#080808] mt-10 mb-6">EMERGENCY AND CONTACT INFORMATION</h2>
        </div>
      </section>

      <Footer />
    </div>
  )
}
